[tool.poetry]
name = "omoospace"
version = "0.1.0"
description = ""
authors = ["manan <icrdr2010@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pyyaml = "^6.0.1"
pypinyin = "^0.49.0"
click = "^8.1.7"
pyvis = "^0.3.2"
networkx = "^3.1"
inquirerpy = "^0.3.4"
rich = "^13.6.0"

[tool.poetry.scripts]
omoospace = "omoospace.commands:cli"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.25.2"
mkdocs = "^1.5.3"
pytest = "^7.4.2"
pytest-dependency = "^0.5.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
